import = [
    "~/.config/alacritty/themes/themes/blood_moon.toml"
]

[window]
opacity = 0.8
blur = true

[window.dimensions]
columns = 140
lines = 36

[font]
size = 12.5

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"